name: "Main pull request workflow"
on: pull_request
jobs:
  lint-monorepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Linters
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [project-one, project-two]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test -- --filter="{${{ matrix.project }}}..."
        env:
          CI: true
